qdrant:
  url: http://localhost:6333
  collection_name: wines
model:
  embedding:
    model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  generative:
    url: https://api.deepseek.com/v1
    model: deepseek-chat